# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15933a5b7e060c2d00067ae8fc70b3716204374c71473959d6bdfcbdc0512b026a24f245e8f2880547f237f835795f7f06235c177bd09c8f5b932cde2a94df62

test:
  secret_key_base: e91dc89644b7970f3102b80358ccd514f338b19808b018bfcefdb8e4b07af598981decb211cfab4d299f8baeff127337bd7c85f181f455b23f183832bc182a65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
