class ReportRecord
  attr_accessor :code_iirsme
  attr_accessor :code_eeva
  attr_accessor :birthdate
  attr_accessor :age
  attr_accessor :diagnosisdate
  attr_accessor :disease_startdate
 
  attr_accessor :day1
  attr_accessor :day2
  attr_accessor :tas1
  attr_accessor :tas2
  attr_accessor :tad1
  attr_accessor :tad2
  attr_accessor :tam1
  attr_accessor :tam2
  attr_accessor :freq_resp1
  attr_accessor :freq_resp2
  attr_accessor :freq_card1
  attr_accessor :freq_card2
  attr_accessor :temp1
  attr_accessor :temp2
  attr_accessor :talla1
  attr_accessor :talla2
  attr_accessor :peso1
  attr_accessor :peso2
  attr_accessor :imc1
  attr_accessor :imc2
  attr_accessor :grasa1
  attr_accessor :grasa2
  attr_accessor :ccin1
  attr_accessor :ccin2
  attr_accessor :ccad1
  attr_accessor :ccad2
  attr_accessor :prom_izq1
  attr_accessor :prom_izq2
  attr_accessor :prom_der1
  attr_accessor :prom_der2
  attr_accessor :eva_enf1
  attr_accessor :eva_enf2
  attr_accessor :eva_dolor1
  attr_accessor :eva_dolor2
  attr_accessor :eva_medico1
  attr_accessor :eva_medico2
  attr_accessor :cdai1
  attr_accessor :cdai2
  attr_accessor :sdai1
  attr_accessor :sdai2
  attr_accessor :haq1
  attr_accessor :haq2
  attr_accessor :nad1
  attr_accessor :nad2
  attr_accessor :nat1
  attr_accessor :nat2
  attr_accessor :vsg1
  attr_accessor :vsg2
  attr_accessor :pcr1
  attr_accessor :pcr2
  attr_accessor :das28_1
  attr_accessor :das28_2
  attr_accessor :das28pcr1
  attr_accessor :das28pcr2
  attr_accessor :tg1
  attr_accessor :tg2
  attr_accessor :ldl1
  attr_accessor :ldl2
  attr_accessor :hdl1
  attr_accessor :hdl2
  attr_accessor :vldl1
  attr_accessor :vldl2
  attr_accessor :indice_ar1
  attr_accessor :indice_ar2
  attr_accessor :ct1
  attr_accessor :ct2
  attr_accessor :glu1
  attr_accessor :glu2
  attr_accessor :apoa1_1
  attr_accessor :apoa1_2
  attr_accessor :apob1
  attr_accessor :apob2
  attr_accessor :tgoast1
  attr_accessor :tgoast2
  attr_accessor :albumina1
  attr_accessor :albumina2
  attr_accessor :fr1
  attr_accessor :fr2
  attr_accessor :c3_1
  attr_accessor :c3_2
  attr_accessor :c4_1
  attr_accessor :c4_2
  attr_accessor :il1_1
  attr_accessor :il1_2
  attr_accessor :il6_1
  attr_accessor :il6_2
  attr_accessor :antipad3_1
  attr_accessor :antipad3_2
  attr_accessor :antipad4_1
  attr_accessor :antipad4_2
  attr_accessor :acpa1
  attr_accessor :acpa2
  attr_accessor :tnfa1
  attr_accessor :tnfa2
  attr_accessor :dna1
  attr_accessor :dna2
  attr_accessor :rna1
  attr_accessor :rna2
  attr_accessor :mirna1
  attr_accessor :mirna2
  attr_accessor :qimt_izq1
  attr_accessor :qimt_izq2
  attr_accessor :qimt_der1
  attr_accessor :qimt_der2
  attr_accessor :qimt_prom1
  attr_accessor :qimt_prom2
  attr_accessor :diam_izq1
  attr_accessor :diam_izq2
  attr_accessor :diam_der1
  attr_accessor :diam_der2
  attr_accessor :qimtmax_izq1
  attr_accessor :qimtmax_izq2
  attr_accessor :qimtmax_der1
  attr_accessor :qimtmax_der2
  attr_accessor :distension1
  attr_accessor :distension2
  attr_accessor :diametro1
  attr_accessor :diametro2
  attr_accessor :distensibilidad1
  attr_accessor :distensibilidad2
  attr_accessor :psisbraq1
  attr_accessor :psisbraq2
  attr_accessor :pdiasbraq1
  attr_accessor :pdiasbraq2
  attr_accessor :psislocal1
  attr_accessor :psislocal2
  attr_accessor :pdiaslocal1
  attr_accessor :pdiaslocal2
  attr_accessor :vo1
  attr_accessor :vo2
  attr_accessor :dc1
  attr_accessor :dc2
  attr_accessor :cc1
  attr_accessor :cc2
  attr_accessor :alfa1
  attr_accessor :alfa2
  attr_accessor :beta1
  attr_accessor :beta2
  attr_accessor :icp1
  attr_accessor :icp2
  attr_accessor :ed1
  attr_accessor :ed2
  attr_accessor :p1
  attr_accessor :p2
  attr_accessor :ap1
  attr_accessor :ap2
  attr_accessor :aix1
  attr_accessor :aix2
  attr_accessor :placa_izq1
  attr_accessor :placa_izq2
  attr_accessor :placa_der1
  attr_accessor :placa_der2
  attr_accessor :pwv1
  attr_accessor :pwv2
  attr_accessor :ttp1
  attr_accessor :ttp2
  attr_accessor :pop1
  attr_accessor :pop2
  attr_accessor :vopcf1
  attr_accessor :vopcf2
  attr_accessor :aixx1
  attr_accessor :aixx2
  attr_accessor :presion_cent1
  attr_accessor :presion_cent2
  attr_accessor :ccp1
  attr_accessor :ccp2
  attr_accessor :app1
  attr_accessor :app2
  attr_accessor :ppas1
  attr_accessor :ppas2
  attr_accessor :ppad1
  attr_accessor :ppad2
  attr_accessor :percentil1
  attr_accessor :percentil2
  attr_accessor :carfem1
  attr_accessor :carfem2
  attr_accessor :caris1
  attr_accessor :caris2
  attr_accessor :isfem1
  attr_accessor :isfem2
  attr_accessor :sevr1
  attr_accessor :sevr2
  attr_accessor :cavii1
  attr_accessor :cavii2
  attr_accessor :cavid1
  attr_accessor :cavid2
  attr_accessor :cavi_prom1
  attr_accessor :cavi_prom2
  attr_accessor :abii1
  attr_accessor :abii2
  attr_accessor :abid1
  attr_accessor :abid2

  def initialize
  end
end